export const actionTypes = {
    SKILLS_AUTOCOMPLETE: "SKILLS_AUTOCOMPLETE",
    SKILLS_AUTOCOMPLETE_SUCCESS: "SKILLS_AUTOCOMPLETE_SUCCESS",
    SKILLS_AUTOCOMPLETE_ERROR: "SKILLS_AUTOCOMPLETE_ERROR"
}