export const actionTypes = {
    SKILLS_AUTOCOMPLETE: "SKILLS_AUTOCOMPLETE",
    SKILLS_AUTOCOMPLETE_SUCCESS: "SKILLS_AUTOCOMPLETE_SUCCESS",
    SKILLS_AUTOCOMPLETE_ERROR: "SKILLS_AUTOCOMPLETE_ERROR",

    JOBS_RELATED_TO_SKILLS: "JOBS_RELATED_TO_SKILLS",
    JOBS_RELATED_TO_SKILLS_SUCCESS: "JOBS_RELATED_TO_SKILLS_SUCCESS",
    JOBS_RELATED_TO_SKILLS_ERROR: "JOBS_RELATED_TO_SKILLS_ERROR"
}